"""
=========================================================
Privacy-Preserving Federated Learning Framework

Module : Aggregation
Version: 3.0 (Final Dissertation Release)

Author : Khawar Akram
=========================================================
"""

# ==========================================================
# FEDERATED AGGREGATION (FedAvg)
# ==========================================================

import copy
import torch

# ==========================================================
# DEBUG
# ==========================================================

DEBUG_SECURE_FEDAVG = True

# ==========================================================
# Trainable Parameter Check
# ==========================================================

def is_trainable_parameter(key, tensor):
    """
    Check whether a parameter should participate in
    Secure Federated Averaging.

    Parameters
    ----------
    key : str
        Parameter name.

    tensor : torch.Tensor

    Returns
    -------
    bool
    """

    if not tensor.dtype.is_floating_point:
        return False

    excluded = (
        "running_mean",
        "running_var",
        "num_batches_tracked",
    )

    return not any(x in key for x in excluded)


def fedavg(client_models, client_samples):
    """
    Weighted Federated Averaging.

    Parameters
    ----------
    client_models : list(dict)
        List of client model state_dicts.

    client_samples : list(int)
        Number of samples owned by each client.

    Returns
    -------
    dict
        Averaged global model weights.
    """

    total_samples = sum(client_samples)

    # Copy first model structure
    averaged_weights = copy.deepcopy(client_models[0])

    # Initialize tensors
    for key in averaged_weights:
        averaged_weights[key] = torch.zeros_like(
            averaged_weights[key]
        )

    # Weighted averaging
    for weights, num_samples in zip(
        client_models,
        client_samples,
    ):

        weight = num_samples / total_samples

        for key in averaged_weights:

            if averaged_weights[key].dtype.is_floating_point:

                averaged_weights[key] += (
                    weights[key] * weight
                )

            else:
                # Integer buffers (e.g. BatchNorm tracking)
                averaged_weights[key] = weights[key]

    return averaged_weights

# ==========================================================
# SECURE FEDERATED AVERAGING
# ==========================================================

def secure_fedavg(
    client_models,
    client_masks,
    client_samples,
):
    """
    Secure Federated Averaging.

    Simulates Secure Aggregation by aggregating masked
    client models and aggregated masks before recovering
    the global model.

    Parameters
    ----------
    client_models : list(dict)
        Masked client model parameters.

    client_masks : list(dict)
        Random masks generated by each client.

    client_samples : list(int)
        Number of samples held by each client.

    Returns
    -------
    dict
        Global model weights.
    """

    if DEBUG_SECURE_FEDAVG:

        print("\n" + "=" * 60)
        print("SECURE FEDERATED AVERAGING")
        print("=" * 60)

    total_samples = sum(client_samples)

    # -------------------------------------------------
    # Initialise Weighted Sums
    # -------------------------------------------------

    weighted_masked_sum = copy.deepcopy(client_models[0])
    weighted_mask_sum = copy.deepcopy(client_masks[0])

    for key in weighted_masked_sum:

        weighted_masked_sum[key] = torch.zeros_like(
            weighted_masked_sum[key]
        )

        weighted_mask_sum[key] = torch.zeros_like(
            weighted_mask_sum[key]
        )

    # -------------------------------------------------
    # Aggregate Masked Models and Masks
    # -------------------------------------------------

    for weights, masks, samples in zip(

        client_models,

        client_masks,

        client_samples,

    ):

        weight = samples / total_samples

        for key in weighted_masked_sum:

            if is_trainable_parameter(
                key,
                weighted_masked_sum[key],
            ):

                weighted_masked_sum[key] += (
                    weights[key] * weight
                )

                weighted_mask_sum[key] += (
                    masks[key] * weight
                )

            else:

                weighted_masked_sum[key] = weights[key]

    # -------------------------------------------------
    # Recover Global Model
    # -------------------------------------------------

    global_weights = copy.deepcopy(weighted_masked_sum)

    for key in global_weights:

        if is_trainable_parameter(
            key,
            global_weights[key],
        ):

            global_weights[key] -= (
                weighted_mask_sum[key]
            )

    # -------------------------------------------------
    # Logging
    # -------------------------------------------------

    if DEBUG_SECURE_FEDAVG:

        print(f"Clients Aggregated : {len(client_models)}")
        print("Weighted Masked Models : ✓")
        print("Weighted Masks         : ✓")
        print("Global Recovery        : ✓")
        print("=" * 60)

    return global_weights